"""Final quiz screen. OWNER: Utkarsh. Nobody else edits this file.

WHAT EXISTS ALREADY (do not rebuild any of it):
    orchestrator.quiz_questions(session) -> list[Question]
        The questions, already generated by finish(). Each Question has
        .id .concept_id .kind ("mcq"|"short"|"explain"|"problem")
        .prompt .options (list[str] | None, mcq only) .expected

    orchestrator.submit_quiz(session, answers) -> LessonReport
        answers is {question_id: the student's answer string}.
        Marks every answer, records them, and returns an updated report.
"""

import streamlit as st

import orchestrator as orch
from ui.i18n import t


def render_quiz(session, lang: str = "en") -> None:
    if session is None:
        st.info(t("quiz.locked", lang))
        return

    questions = orch.quiz_questions(session)
    if not questions:
        st.info(t("quiz.locked", lang))
        return

    st.subheader(t("quiz.title", lang))
    st.caption(f"{len(questions)} question(s) across every concept taught.")

    with st.form("final_quiz_form"):
        user_answers = {}
        for idx, q in enumerate(questions, start=1):
            st.markdown(f"**Question {idx}:** {q.prompt}")

            if q.kind == "mcq" and q.options:
                chosen = st.radio(
                    t("lesson.your_answer", lang),
                    options=q.options,
                    key=f"quiz_opt_{q.id}",
                    index=None,
                    label_visibility="collapsed"
                )
                user_answers[q.id] = chosen or ""
            else:
                text_ans = st.text_input(
                    t("lesson.your_answer", lang),
                    key=f"quiz_txt_{q.id}",
                    placeholder="Type your response here...",
                    label_visibility="collapsed"
                )
                user_answers[q.id] = text_ans or ""
            st.divider()

        submitted = st.form_submit_button(t("quiz.submit", lang), type="primary",
                                          use_container_width=True)

    if submitted:
        # Check if all questions were answered
        unanswered = sum(1 for v in user_answers.values() if not str(v).strip())
        if unanswered > 0:
            st.warning(f"Note: You left {unanswered} question(s) blank.")

        # submit_quiz marks every answer through the LLM, so it can fail for
        # all the ordinary reasons — quota, timeout, a bad key. Unguarded, that
        # put a raw traceback on the screen and lost the answers the student
        # had just typed. They are still in the widgets; let them press again.
        try:
            with st.spinner(t("lesson.marking", lang)):
                report = orch.submit_quiz(session, user_answers)
        except Exception as exc:
            st.error(
                f"**Could not mark the quiz.** {type(exc).__name__}: "
                f"{str(exc)[:300]}\n\nYour answers are still here — press "
                f"submit again, or check **⚙️ APIs** in the sidebar."
            )
            return

        # Fold the quiz result into the Report tab as well, so the score a
        # student sees there is the one they just earned rather than the
        # mid-lesson score from before the quiz existed.
        st.session_state.report = report
        # The report tab caches the stitched lesson video; the score behind it
        # has just changed, so let it rebuild rather than show the old one.
        st.session_state.pop("lesson_video", None)
        st.success(f"{t('report.score', lang)}: **{report.score:.1f}%**")

        col1, col2 = st.columns(2)
        with col1:
            st.markdown(f"#### {t('report.strong', lang)}")
            if report.strong:
                for s in report.strong:
                    st.write(f"- {s}")
            else:
                st.caption("Keep practicing to master these concepts.")

            if report.misconceptions:
                st.markdown(f"#### {t('panel.misconception', lang)}")
                for m in report.misconceptions:
                    st.warning(f"⚠️ {m}")

        with col2:
            if report.weak:
                st.markdown(f"#### {t('report.weak', lang)}")
                for w in report.weak:
                    st.write(f"- {w}")

            if report.revise:
                st.markdown(f"#### {t('report.revise', lang)}")
                for r in report.revise:
                    st.info(f"📌 {r}")

            if report.next_topic:
                st.markdown(f"#### {t('report.next', lang)}")
                st.write(f"**{report.next_topic}**")
