"""Final quiz screen.  OWNER: Utkarsh.  Nobody else edits this file.

WHAT EXISTS ALREADY (do not rebuild any of it):
    orchestrator.quiz_questions(session) -> list[Question]
        The questions, already generated by finish(). Each Question has
        .id .concept_id .kind ("mcq"|"short"|"explain"|"problem")
        .prompt .options (list[str] | None, mcq only) .expected

    orchestrator.submit_quiz(session, answers) -> LessonReport
        answers is {question_id: the student's answer string}.
        Marks every answer, records them, and returns an updated report.

WHAT YOU BUILD: the body of render_quiz below.

    - one input per question; st.radio for kind == "mcq" (use q.options),
      st.text_input otherwise
    - one submit button inside an st.form so a click cannot fire twice
    - after submitting, show which were right and the updated score
    - if orchestrator.quiz_questions(session) is empty, say the lesson is not
      finished yet and return

DO NOT import teacher/, planner/ or ingest/ here. Go through orchestrator.
"""

import streamlit as st

import orchestrator as orch


def render_quiz(session) -> None:
    questions = orch.quiz_questions(session)
    if not questions:
        st.caption("Finish the lesson to unlock the final quiz.")
        return

    st.subheader("Final quiz")
    st.caption(f"{len(questions)} questions")
    st.info("Not built yet — Utkarsh. See the docstring at the top of this file.")
